apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    app_name: guestbook
    tier: frontend
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app_name: guestbook
    tier: frontend
  type:  NodePort
