apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app_name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app_name: redis
      role: slave
      tier: backend    
  template:
    metadata:
      labels:
        app_name: redis
        role: slave
        tier: backend
    spec:
      containers: 
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v3
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 6379
        env:
        - name: GET_HOSTS_FROM
          value: env
