apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app_name: redis
    role: slave
    tier: backend
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app_name: redis
    role: slave
    tier: backend
