apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app_name: redis
    role: master
    tier: backend
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app_name: redis
    role: master
    tier: backend
